### ISSUE TITLE
报错lib下缺失css文件

### ISSUE THREAD

**Issue by sunzlgh** [jingoal-silk/Scroller#4]
npm install silk-scroller : ^1.0.6 下载下来 lib下 没有Scroller.css

**Comment by Notdefind** [comment]
缺少css文件,大兄弟 你仿佛在逗我笑

**Comment by kanily** [comment]
ERROR in ./~/silk-scroller/lib/lang/index.js
Module not found: Error: Cannot resolve module 'json' in C:\Users\BJ-D0203\Documents\work\react-h5\node_modules\silk-scroller\lib\lang
 @ ./~/silk-scroller/lib/lang/index.js 9:13-36

ERROR in ./~/silk-scroller/lib/lang/index.js
Module not found: Error: Cannot resolve module 'json' in C:\Users\BJ-D0203\Documents\work\react-h5\node_modules\silk-scroller\lib\lang
 @ ./~/silk-scroller/lib/lang/index.js 13:13-36

ERROR in ./~/silk-scroller/lib/lang/index.js
Module not found: Error: Cannot resolve module 'json' in C:\Users\BJ-D0203\Documents\work\react-h5\node_modules\silk-scroller\lib\lang
 @ ./~/silk-scroller/lib/lang/index.js 17:13-36

**Comment by houyulei** [comment]
It has been fixed in 1.0.7
